blogango/urls.py
from datetime import datetime
from django.conf.urls import patterns, url
from django.contrib.sitemaps import GenericSitemap
from blogango import feeds
from blogango.models import BlogEntry

blog_info_dict = {
    'queryset': BlogEntry.objects.all(),
    'date_field': 'publish_date',
}
sitemaps = {
    'blog': GenericSitemap(blog_info_dict, priority=0.5)
}

urlpatterns = patterns('blogango.views',
    url(r'^$', 'index', name="blogango_index"),
    url(r'^install/$', 'install_blog', name='blogango_install'),
    url(r'^page/(?P<page>\d+)/$', 'index',  name='blogango_page'),
    url(r'^(?P<year>\d{4})/(?P<month>\d+)/(?P<slug>[-\w]+)/$', 'details',
        name='blogango_details'),
    url(r'^blogroll/$', 'create_blogroll', name='blogango_blogroll'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', 'tag_details',
        name='blogango_tag_details'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/(?P<page>\d+)/$', 'tag_details',
        name='blogango_tag_details_page'),
    url(r'^author/(?P<username>[\w.@+-]+)/$', 'author', name='blogango_author_page'),

    url(r'^admin/$', 'admin_dashboard', name='blogango_admin_dashboard'),
    url(r'^admin/entry/new/$', 'admin_entry',
        name='blogango_admin_entry_new'),
    url(r'^admin/entry/edit/(?P<pk>\d+)/$', 'admin_edit',
        name='blogango_admin_entry_edit'),
    url(r'^admin/entry/manage/$', 'admin_manage_entries',
        name='blogango_admin_entry_manage'),
    url(r'^admin/entry/manage/(?P<username>[\w.@+-]+)/$',
        'admin_manage_entries', name='blogango_admin_author_entry_manage'),
    url(r'^admin/comments/manage/$', 'admin_manage_comments',
        name='blogango_admin_comments_manage'),
    url(r'^admin/comments/manage/(?P<entry_id>\d+)/$',
        'admin_manage_comments', name='blogango_admin_entry_comments_manage'),
    url(r'^admin/preferences/edit/$', 'admin_edit_preferences',
        name='blogango_admin_edit_preferences'),
    url(r'^admin/comment/approve/$', 'admin_comment_approve',
        name='blogango_admin_comment_approve'),
    url(r'^admin/comment/block/$', 'admin_comment_block',
        name='blogango_admin_comment_block'),
)

# sitemap.xml
urlpatterns += patterns('django.contrib.sitemaps.views',
    url(r'^sitemap\.xml$', 'sitemap', {'sitemaps': sitemaps}),
)

# Archive view
urlpatterns += patterns('blogango.views',
    url(r'^archive/(?P<year>\d+)/(?P<month>\w+)/$', 'monthly_view', name='blogango_archives')
)

urlpatterns += patterns('django_xmlrpc.views',
    url(r'^xmlrpc/$', 'handle_xmlrpc', {}, name='xmlrpc'),
)

urlpatterns += patterns('',
    url(r'^rss/latest/$', feeds.main_feed(), name='blogango_feed')
)

urlpatterns += patterns('',
    url(r'^rss/latest/(?P<tag>[-\w]+)/$', feeds.CatFeed(), name='blogango_tag_feed')
)

urlpatterns += patterns('blogango.views',
    url(r'^(?P<slug>[-\w]+)/$', 'details', name='blogango_page_details'),
)

blogango/models.py
from datetime import datetime, timedelta
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse

from taggit.managers import TaggableManager
from markupfield.fields import MarkupField
from markupfield.markup import DEFAULT_MARKUP_TYPES


class BlogManager(models.Manager):
    def get_blog(self):
        blogs = self.all()
        if blogs:
            return blogs[0]
        return None


class Blog(models.Model):
    """Blog wide settings.
     title:title of the Blog.
     tag_line: Tagline/subtitle of the blog.
               This two are genearlly displayed on each page's header.
     entries_per_page=Number of entries to display on each page.
     recents: Number of recent entries to display in the sidebar.
     recent_comments: Number of recent comments to display in the sidebar.
    """

    title = models.CharField(max_length=100)
    tag_line = models.CharField(max_length=100)
    entries_per_page = models.IntegerField(default=10)
    recents = models.IntegerField(default=5)
    recent_comments = models.IntegerField(default=5)

    objects = BlogManager()

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):

        """There should not be more than one Blog object"""
        if Blog.objects.count() == 1 and not self.id:
            raise Exception("Only one blog object allowed.")
        # Call the "real" save() method.
        super(Blog, self).save(*args, **kwargs)


class BlogPublishedManager(models.Manager):
    use_for_related_fields = True

    def get_queryset(self):
        return super(BlogPublishedManager, self).get_queryset().filter(
            is_published=True,
            publish_date__lte=datetime.now())


class BlogEntry(models.Model):
    """Each blog entry.
    Title: Post title.
    Slug: Post slug.
          These two if not given are inferred directly from entry text.
    text = The main data for the post.
    summary = The summary for the text. probably can be derived from text,
              but we dont want do do that each time main page is displayed.
    created_on = The date this entry was created. Defaults to now.
    Created by: The user who wrote this.
    is_page: Is this a page or a post? Pages are the more important posts,
             which might be displayed differently. Defaults to false.
    is_published: Is this page published.
                  If yes then we would display this on site, otherwise no.
                  Defaults to true.
    comments_allowed: Are comments allowed on this post? Defaults to True
    is_rte: Was this post done using a Rich text editor?"""

    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    text = MarkupField(default_markup_type=getattr(settings,
                                                   'DEFAULT_MARKUP_TYPE',
                                                   'plain'),
                       markup_choices=getattr(settings, "MARKUP_RENDERERS",
                                              DEFAULT_MARKUP_TYPES))
    summary = models.TextField()
    created_on = models.DateTimeField(default=datetime.max, editable=False)
    created_by = models.ForeignKey(User, unique=False)
    is_page = models.BooleanField(default=False)
    is_published = models.BooleanField(default=True)
    publish_date = models.DateTimeField(null=True)
    comments_allowed = models.BooleanField(default=True)
    is_rte = models.BooleanField(default=False)

    meta_keywords = models.TextField(blank=True, null=True)
    meta_description = models.TextField(blank=True, null=True)

    tags = TaggableManager()

    default = models.Manager()
    objects = BlogPublishedManager()

    class Meta:
        ordering = ['-created_on']
        verbose_name_plural = 'Blog entries'

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.title is None or self.title == '':
            self.title = _infer_title_or_slug(self.text.raw)

        if self.slug is None or self.slug == '':
            self.slug = slugify(self.title)

        i = 1
        while True:
            created_slug = self.create_slug(self.slug, i)
            slug_count = BlogEntry.objects.filter(slug__exact=created_slug).exclude(pk=self.pk)
            if not slug_count:
                break
            i += 1
        self.slug = created_slug

        if not self.summary:
            self.summary = _generate_summary(self.text.raw)
        if not self.meta_keywords:
            self.meta_keywords = self.summary
        if not self.meta_description:
            self.meta_description = self.summary

        if self.is_published:
            #default value for created_on is datetime.max whose year is 9999
            if self.created_on.year == 9999:
                self.created_on = self.publish_date
        # Call the "real" save() method.
        super(BlogEntry, self).save(*args, **kwargs)

    def create_slug(self, initial_slug, i=1):
        if not i == 1:
            initial_slug += "-%s" % (i,)
        return initial_slug

    def get_absolute_url(self):
        return reverse('blogango_details',
                       kwargs={'year': self.created_on.strftime('%Y'),
                               'month': self.created_on.strftime('%m'),
                               'slug': self.slug})

    def get_edit_url(self):
        return reverse('blogango_admin_entry_edit', args=[self.id])

    def get_num_comments(self):
        cmnt_count = Comment.objects.filter(comment_for=self, is_spam=False).count()
        return cmnt_count

    def get_num_reactions(self):
        reaction_count = Reaction.objects.filter(comment_for=self).count()
        return reaction_count

    # check if the blog have any comments in the last 24 hrs.
    def has_recent_comments(self):
        yesterday = datetime.now()-timedelta(days=1)
        return Comment.objects.filter(
            comment_for=self, is_spam=False, created_on__gt=yesterday
        ).exists()

    # return comments in the last 24 hrs
    def get_recent_comments(self):
        yesterday = datetime.now()-timedelta(days=1)
        cmnts = Comment.objects.filter(
            comment_for=self, is_spam=False, created_on__gt=yesterday
        ).order_by('-created_on')
        return cmnts


class CommentManager(models.Manager):
    def get_queryset(self):
        return super(CommentManager, self).get_queryset().filter(is_public=True)


class BaseComment(models.Model):
    text = models.TextField()
    comment_for = models.ForeignKey(BlogEntry)
    created_on = models.DateTimeField(auto_now_add=True)
    user_name = models.CharField(max_length=100)
    user_url = models.URLField()

    class Meta:
        ordering = ['created_on']
        abstract = True

    def __unicode__(self):
        return self.text


class Comment(BaseComment):
    """Comments for each blog.
    text: The comment text.
    comment_for: the Post/Page this comment is created for.
    created_on: The date this comment was written on.
    created_by: THe user who wrote this comment.
    user_name = If created_by is null, this comment was by anonymous user.
                Name in that case.
    email_id: Email-id, as in user_name.
    is_spam: Is comment marked as spam?
             We do not display the comment in those cases.
    is_public: null for comments waiting to be approved, True if approved,
               False if rejected
    user_ip: Ip address from which this comment was made
    user_agent: User agent of the commenter
    """

    created_by = models.ForeignKey(User, unique=False, blank=True, null=True)
    email_id = models.EmailField()
    is_spam = models.BooleanField(default=False)
    is_public = models.NullBooleanField(null=True, blank=True)
    user_ip = models.IPAddressField(null=True)
    user_agent = models.CharField(max_length=200, default='')

    default = models.Manager()
    objects = CommentManager()

    def save(self, *args, **kwargs):
        if self.is_spam:
            self.is_public = False
        super(Comment, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blogango_comment_details', args=[self.id, ])


class Reaction(BaseComment):
    """
    Reactions from various social media sites
    """
    reaction_id = models.CharField(max_length=200, primary_key=True)
    source = models.CharField(max_length=200)
    profile_image = models.URLField(blank=True, null=True)


class BlogRoll(models.Model):
    url = models.URLField(unique=True)
    text = models.CharField(max_length=100)
    is_published = models.BooleanField(default=True)

    def __unicode__(self):
        return self.text

    def get_absolute_url(self):
        return self.url


#Helper methods
def _infer_title_or_slug(text):
    return '-'.join(text.split()[:5])


def _generate_summary(text):
    return ' '.join(text.split()[:100])

blogango/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.admin import widgets

from blogango.models import Blog, BlogRoll, BlogEntry


class WideTextArea(forms.Textarea):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('attrs', {}).update({'rows': '20', 'cols': '80'})
        super(WideTextArea, self).__init__(*args, **kwargs)


class EntryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EntryForm, self).__init__(*args, **kwargs)
        self.fields['created_by'].queryset = User.objects.filter(is_staff=True)
        self.fields['publish_date'].widget = widgets.AdminSplitDateTime()

    title = forms.CharField(max_length=100,
                            required=False,
                            widget=forms.TextInput(attrs={'size': '40'}))
    text = forms.CharField(widget=WideTextArea(attrs={'class': 'resizable'}))

    class Meta:
        model = BlogEntry
        exclude = ('slug', 'summary')


class CommentForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea'}),
                           label='Comment')
    name = forms.CharField(max_length=100,
                           widget=forms.TextInput(attrs={'class':
                                                         'textfield'}))
    url = forms.URLField(required=False,
                         widget=forms.TextInput(attrs={'class': 'textfield'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':
                                                           'textfield'}))


class InstallForm(forms.ModelForm):

    class Meta:
        model = Blog
        exclude = ('entries_per_page', 'recents', 'recent_comments')


class PreferencesForm(forms.ModelForm):

    class Meta:
        model = Blog
        fields = ('title', 'tag_line', 'entries_per_page', 'recents', 'recent_comments')


class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogRoll
        exclude = ('is_published',)

blogango/templates/blogango/admin/base.html
{% load blogango_filters %}
{% blogango_extra_context %}

<!doctype html>
<html>
<head>
  {% block html_head %}

  <title>{% block title %}{% endblock %} &mdash; {{ blog.title }} {{ _("Administration") }}</title>

  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}blogango/admin/preview.css">
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}blogango/admin/style.css">
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}blogango/css/jquery.autocomplete.css">

  <script type="text/javascript" src="{{ STATIC_URL }}blogango/js/jquery.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}blogango/js/jquery.autocomplete.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}blogango/js/jquery.textarearesizer.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}blogango/js/Admin.js"></script>
  {% endblock %}
  {% block page_head %}{% endblock %}
  {% block extra_script %}{% endblock %}
</head>
<body>
  <div class="header">
    <div class="title">{{ blog.title }} Administration</div>
    <div class="metanav">
      <a href="{% url "blogango_index" %}">{{ _("View Blog") }}</a> |
      <a href="{% url "admin:logout" %}">{{ _("Logout") }}</a>
    </div>
  </div>
  <div class="body">
    <ul class="navbar standalonebar">
      {% url "blogango_admin_dashboard" as dashboard_url %}
      <li {% if request.path == dashboard_url %}class="active"{% endif %}>
          <a href="{{ dashboard_url }}">{{ _("Dashboard") }}</a>
      </li>
      {% url "blogango_admin_entry_new" as write_url %}
      <li {% if request.path == write_url %}class="active"{% endif %}>
          <a href="{{ write_url }}">{{ _("Write") }}</a>
      </li>
      {% url "blogango_admin_entry_manage" as manage_entry_url %}
      {% if author %}
          {% url "blogango_admin_author_entry_manage" author.username as manage_author_entry_url %}
      {% endif %}
      <li {% if request.path == manage_entry_url or request.path == manage_author_entry_url %}class="active"{% endif %}>
          <a href="{{ manage_entry_url }}">{{ _("Manage") }}</a>
      </li>
      {% url "blogango_admin_comments_manage" as manage_comments_url %}
      {% if blog_entry %}
          {% url "blogango_admin_entry_comments_manage" blog_entry.pk as manage_entry_comments_url %}
      {% endif %}
      <li {% if request.path == manage_comments_url or request.path == manage_entry_comments_url %}class="active"{% endif %}>
          <a href="{{ manage_comments_url }}">{{ _("Comments") }}</a>
      </li>
      {% url "blogango_admin_edit_preferences" as edit_preferences_url %}
      <li {% if request.path == edit_preferences_url %}class="active"{% endif %}>
          <a href="{{ edit_preferences_url }}">{{ _("Options") }}</a>
      </li>
    </ul>
    {% block subnavbar %}{% endblock %}
    <div class="contents">
      {% block contents %}{% endblock %}
    </div>
  </div>
  <div class="footer">
    <p>
        <a href="http://{{ site.domain }}/">{{ site.name }}</a>
        Powered by blogango | &copy; 2010 by {{ site.name }}
    </p>
  </div>
</body>
</html>

blogango/templates/blogango/admin/edit_entry.html
{% extends "blogango/admin/base.html" %}
{% block title %}
    {% if blogentry %}
        Editing blogentry:: {{ form.initial.title }}
    {% else %}
        New Entry
    {% endif %}
    &#8203;{{ title_suffix }}
{% endblock %}
{% block page_head %}
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}admin/css/base.css" />
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}admin/css/forms.css" />

<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="{{STATIC_URL}}admin/js/core.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}admin/js/calendar.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}admin/js/admin/DateTimeShortcuts.js"></script>
{% endblock %}
{% block extra_script %}
    <script>
        $(document).ready(function(){
            var tags_json = '{{tags_json|safe}}';
            var tag_list = JSON.parse(tags_json);
            $("#id_tags").autocomplete(tag_list, {
                multiple: true
            });
        });
    </script>
{% endblock %}
{% block subnavbar %}
    <ul class="ctxnavbar">
      <li{% if 'page' not in request.GET %} class="active"{% endif %}>
          <a href="{{ request.path }}">Entry</a>
      </li>
      <li{% if 'page' in request.GET %} class="active"{% endif %}>
          <a href="{{ request.path }}?page">Page</a>
      </li>
    </ul>
{% endblock %}
{% block contents %}
      <div class="notification-messages">      
	    {% if 'done' in request.GET %}
	        <div class="message message-info">Blog entry saved successfully</div>
	    {% endif %}
      </div>
    {% if blogentry %}
        <h1>
            {{ blogentry.title }} &mdash; &#8203; Edit Entry
            {% if blogentry.is_published %}
                <a href="{{ blogentry.get_absolute_url }}" class="preview">{{ _("View Entry") }}</a>
            {% else %}
                <a href="{{ blogentry.get_absolute_url }}?preview" class="preview" target="_blank">{{ _("Preview Entry") }}</a>
            {% endif %}
        </h1>
    {% endif %}
    {% if form.errors %}
        Please correct the following errors:
        <ul class="errors">
            {% for field, error in form.errors.iteritems %}
                <li>{{ field }} {{ error.as_text }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
		<div class="formbox formbox-title">
		      <h3><label for="id_title">Title</label></h3>
		      {{ form.title }}
		</div>
		<div class="formbox">
		      <h3><label for="id_text">Text</label></h3>
		      {{ form.text }}
		</div>
		<div class="formbox">
		      <h3><label for="id_text_markup_type">Markup Parser</label></h3>
		      {{ form.text_markup_type }}
		</div>
		<div class="formbox">
		      <h3><label for="id_tags">Tags</label></h3>
		      {{ form.tags }}
		</div>
		<div class="formbox toggleable collapsed">
		      <h3><label for="id_created_by">Author</label></h3>
		      {{ form.created_by }}
		</div>	
		<div class="formbox">
		      <h3><label for="id_published_date">Publish date</label></h3>
              {{ form.publish_date }}
		</div>
		<div class="formbox toggleable collapsed">
		      <h3><label for="id_meta_keywords">Keywords</label></h3>
		      {{ form.meta_keywords }}
		</div>
		<div class="formbox toggleable collapsed">
		      <h3><label for="id_meta_description">Description</label></h3>
		      {{ form.meta_description }}
		</div>
		<div class="formbox">
		      <h3><label for="id_comments_allowed">Allow Comments?</label></h3>
		      {{ form.comments_allowed }}
		</div>
		{% if 'page' in request.GET %}
		    <input type="hidden" name="page" value="1" />
		{% endif %}
		<div class="secondary">
		  <div class="actions">
		    <input type="submit" value="{% if blogentry.is_published %}Unpublish{% else %}Save{% endif %}" name="save">
		    <input type="submit" value="Save and Publish" name="publish">
		    <input type="reset" value="Cancel" name="cancel">
		  </div>
		</div>
	</form>
{% endblock %}

blogango/templates/blogango/admin/edit_preferences.html
{% extends "blogango/admin/base.html" %}
{% block title %}{{ _("Basic Options") }}{% endblock %}
{% block contents %}
  <h1>{{ _("Basic Options") }}</h1>
  <p>
    From here you can configure the basic blog settings like the blog
    title and tagline.
  </p>
  <div class="notification-messages">      
    {% if 'done' in request.GET %}
        <div class="message message-info">Preferences saved successfully</div>
    {% endif %}
  </div>  
	{% if form.errors %}
	    Please correct the following errors:
	    <ul class="errors">
	        {% for field, error in form.errors.iteritems %}
	            <li>{{ field }} {{ error.as_text }}</li>
	        {% endfor %}
	    </ul>
	{% endif %}
  <form method="POST">
    {% csrf_token %}
      <dl>
	    <dt>
	      <label for="id_title">Blog title</label>
	    </dt>
	    <dd>
	      {{ form.title }}
	    </dd>
	    <dt>
	      <label for="id_tag_line">Blog tagline</label>
	    </dt>
	    <dd>
	      {{ form.tag_line }}
	    </dd>
	    <dt>
	      <label for="id_entries_per_page">Entries per page</label>
	    </dt>
	    <dd>
	      {{ form.entries_per_page }}
	    </dd>
	    <dt>
	      <label for="id_recents">Number of recent entries</label>
	    </dt>
	    <dd>
	      {{ form.recents }}
	    </dd>
	    <dt>
	      <label for="id_recent_comments">Number of recent comments</label>
	    </dt>
	    <dd>
	      {{ form.recent_comments }}
	    </dd>
	  </dl>
	    <div class="actions">
	      <input type="submit" value="{{ _('Save') }}">
	    </div>
  </form>
{% endblock %}

blogango/templates/blogango/admin/entry_snippet.html
<tr {% if not entry.is_published %}class="draft"{% endif %}>
  <td class="title">
      <a href="{{ entry.get_edit_url }}">
        {% if not entry.is_published %}
        <em>{{ entry.title }}</em>
        {% else %}
        {{ entry.title }}
        {% endif %}
      </a>
    <span class="meta">[<a href="{{ entry.get_edit_url }}">edit</a>]</span>
    {% if entry.is_published %}
    <span class="meta">[<a href="{{ entry.get_absolute_url }}">show</a>]</span>
    {% else %}
    <span class="meta">[<a href="{{ entry.get_absolute_url }}?preview">preview</a>]</span>
    {% endif %}
  </td>
  <td class="author"><a href="{% url "blogango_admin_author_entry_manage" entry.created_by.username %}">{{ entry.created_by }}</a></td>
  <td class="categories">
  {% for tag in entry.tags.all %}
      <a href="{% url "blogango_tag_details" tag.slug %}">{{ tag.name }}</a>
  {% endfor %}
  </td>
  <td class="comments"><a href="{% url "blogango_admin_entry_comments_manage" entry.pk %}">{{ entry.get_num_comments }}</a></td>
  <td class="date">
      {% ifequal entry.created_on.year 9999 %}
          Not published yet.
      {% else %}
          {{ entry.created_on }}
      {% endifequal %}
  </td>
</tr>

blogango/templates/blogango/admin/index.html
{% extends "blogango/admin/base.html" %}
{% load i18n %}
{% block title %}{{ _("Dashboard") }}{% endblock %}
{% block contents %}
  <div class="dashboard">
    <h1>{{ _("Dashboard") }}</h1>
    <div class="panel">
      <div class="text">
        <p>
          Howdy. Welcome to the administration interface, {{ request.user.username }}.
          You have written <strong>{{ request.user.blogentry_set.count }}</strong> post{{ request.user.blogentry_set.count|pluralize }} so far.
      </div>
      <h2>{{ _('Quickstart') }}</h2>
      <ul>
        <li><a href="{% url "blogango_admin_entry_new" %}">{{ _("New Entry") }}</a>
        <li><a href="{% url "blogango_admin_comments_manage" %}">{{ _("Moderate Comments") }}</a>
        <li><a href="{% url "blogango_admin_entry_manage" %}">{{ _("Manage Entries") }}</a>
        <li><a href="{% url "blogango_admin_edit_preferences" %}">{{ _("Configure blogango") }}</a>
      </ul>
    </div>
    <div class="links">
      {% if recent_drafts %}
      <h2>{{ _("Drafts") }}</h2>
      <ul class="drafts">
      {% for draft in recent_drafts %}
        <li>
            <a href="{{ draft.get_edit_url }}">{{ draft.title }}</a>
            <span class="meta">[<a href="{{ draft.get_absolute_url }}?preview">{{ _('show') }}</a>]</span>,
            {{ draft.created_on }}
        </li>
      {% endfor %}
      </ul>
      {% endif %}
      {% if recent_entries %}
      <h2>{{ _("Recent Posts") }}</h2>
      <ul class="last_posts">
      {% for post in recent_entries %}
        <li>
            <a href="{{ post.get_edit_url }}">{{ post.title }}</a>
            <span class="meta">[<a href="{{ post.get_absolute_url }}">{{ _('show') }}</a>]</span>,
          {{ post.created_on }}
      {% endfor %}
      </ul>
      {% endif %}
    </div>
    <div class="clear"></div>
  </div>
{% endblock %}

blogango/templates/blogango/admin/manage_entries.html
{% extends "blogango/admin/base.html" %}
{% block title %}{{ _("Manage Entries") }}{% endblock %}
{% block contents %}
<h1>{{ _("Manage Entries") }}{% if author %} by {{author}}{% endif %}</h1>
	<table class="postlist">
	    <tbody>
		    <tr>
		      <th class="title">Title</th>
		      <th class="author">Author</th>
		      <th class="categories">Categories</th>
		      <th class="comments">Comments</th>
		      <th class="date">Date</th>
		    </tr>
		    {% for entry in entries %}
		        {% include "blogango/admin/entry_snippet.html" %}
		    {% endfor %}
        </tbody>
    </table>
  <form action="{% url "blogango_admin_entry_new" %}" method="get">
    <div class="actions">
      <input type="submit" value="{{ _('New Entry') }}">
    </div>
  </form>
{% endblock %}